name = "GeometricBase"
uuid = "9a0b12b7-583b-4f04-aa1f-d8551b6addc9"
version = "0.12.10"
authors = ["Michael Kraus"]

[deps]
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
Unicode = "1.10"
julia = "1.10"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SafeTestsets", "Test"]
